Dev
Mkspulemet/news pull request #1
Opened 2024-03-14 18:10 UTC by Mkspulemet

app_news

2024-03-26 17:15 UTC, udevgeektutor requested changes

2024-03-26 17:15 UTC, udevgeektutor commented on mywebsite/app_news/admin.py
> +
После импортов должно быть только 2 пустые строки
```suggestion
```

2024-03-26 17:15 UTC, udevgeektutor commented on mywebsite/mywebsite/settings.py
> +
Лишняя строка
```suggestion
```

2024-03-26 17:50 UTC, Mkspulemet commented on mywebsite/app_news/admin.py
> +
поправил

2024-03-26 17:50 UTC, udevgeektutor approved these changes

2024-03-26 17:50 UTC, Mkspulemet commented on mywebsite/mywebsite/settings.py
> +
поправил

2024-03-26 17:52 UTC, merged

2024-03-28 17:01 UTC, udevgeektutor reviewed
+весь проект привести в единообразие по ковычкам. В части файлов они двойные в части одинарные. Должно быть единообразие

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/app_news/models.py
> +    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
Длина строки более 79 символов. Не соответсвует pep8

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/app_news/models.py
> +                       )
Лучше так
```suggestion
    def get_absolute_url(self):
        return reverse(
            "app_news:article_detail",
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug,
            ],
        )
```

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/mywebsite/urls.py
> +    path('news/', include('app_news.urls', namespace='app_news'))
```suggestion
    path('news/', include('app_news.urls', namespace='app_news')),
```

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/app_news/urls.py
> +    path('<int:year>/<int:month>/<int:day>/<slug:article_slg>', article_detail, name='article_detail'),
Строка явно больше 79 символов, не соотвествует pep8.

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/app_news/urls.py
> +app_name = 'news'
После импортов 2 пустые строки.

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/app_news/admin.py
> +from  django.contrib import admin
```suggestion
from django.contrib import admin
```

2024-03-28 17:01 UTC, udevgeektutor commented on mywebsite/mywebsite/urls.py
> +urlpatterns = [
должно быть 2 пустые строки по pep.
```suggestion
from django.urls import path, include


urlpatterns = [
```

2024-04-02 15:52 UTC, udevgeektutor reviewed
Подскажи видишь эти комменты?