homework with pagination
Mkspulemet/news pull request #2
Opened 2024-04-04 16:34 UTC by Mkspulemet

2024-04-04 18:35 UTC, udevgeektutor commented
Лучше делать небольшие коммиты, с небольшими изменениями, чем 1 большой.
например 100 фиксов в одном коммите. из 100, нам нужно отменить 3 фикса, так как они не очень. В итоге что все 100 придется откатить и потом заново накатить?
если бы было для 100 фиксов было по 1 коммиту на фикс, то 97 хороших остались бы нетронуты, и откатить нужно было бы только 3.
В последующем лучше делать побольше коммитов с комментариями)

2024-04-04 18:35 UTC, udevgeektutor commented
+добавь описание к пулреквесту, чтобы пояснить что сделано и тп

2024-04-09 17:26 UTC, udevgeektutor commented
Не вижу файла requirements.txt  с зависимостями проект, его следует добавить)

2024-04-09 17:44 UTC, udevgeektutor requested changes

2024-04-09 17:44 UTC, udevgeektutor commented on mywebsite/app_news/urls.py
>           article_detail, name='article_detail'),
Ок, но читабельнике будет так
```suggestion
    path(
        '<int:year>/<int:month>/<int:day>/<slug:article_slg>',
        article_detail,
        name='article_detail',
    ),
```

2024-04-09 17:44 UTC, udevgeektutor commented on mywebsite/app_news/views.py
> +            cd = form.cleaned_data
Улучшит читаемость
```suggestion
def article_share(request, article_id):
    sent = False
    article = get_object_or_404(Article, id=article_id,
                                status=Article.Status.PUBLISHED)
                                
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        
        if form.is_valid():
            cd = form.cleaned_data
```

2024-04-09 17:44 UTC, udevgeektutor commented on mywebsite/app_news/views.py
> +        {'article': article, 'form': form, 'sent': sent}, )
```suggestion
            sent = True
    else:
        form = EmailPostForm()
        
    return render(
        request, 
        'app_news/article/share.html',
        {'article': article, 'form': form, 'sent': sent}, 
    )
```

2024-04-09 17:44 UTC, udevgeektutor commented on mywebsite/app_news/templates/app_news/article/detail.html
Прогони форматтером.
в VS code - ctrl+alf+f

2024-04-10 16:39 UTC, Mkspulemet commented on mywebsite/app_news/views.py
> +            cd = form.cleaned_data
исправлено cf515df15e7b92619ec6ed492b1fddd1c98b005b

2024-04-10 16:39 UTC, Mkspulemet commented on mywebsite/app_news/urls.py
>           article_detail, name='article_detail'),
исправлено cf515df15e7b92619ec6ed492b1fddd1c98b005b

2024-04-10 16:39 UTC, Mkspulemet commented on mywebsite/app_news/views.py
> +        {'article': article, 'form': form, 'sent': sent}, )
исправлено cf515df15e7b92619ec6ed492b1fddd1c98b005b

2024-04-10 16:41 UTC, Mkspulemet commented on mywebsite/app_news/templates/app_news/article/detail.html
исправлено 8fad44e2be4d1951607a08b3fa519119b5327f37

2024-04-16 14:36 UTC, udevgeektutor approved these changes

2024-04-16 16:09 UTC, merged